### PR TITLE
Fix some operators' precedence/associativity

### PR DESCRIPTION
**Pull request by KevOrr**
See #37. This PR:

- Gets rid of unused precedence levels
- Introduces new precedence levels for `or`, `xor`, `and`, assignment, `??`, `|`, `^`, `&`, equality (`==`, `!=`, `<=>`, ...) vs inequality/comparison operators (`>`, `<=`, ...), and `instanceof`
- Sets corresponding operators at the correct precedence
- Makes assignment and compound/augmented assignment right-associative operators
- Makes `instanceof` a left-associative operator
- Makes `??` a right-associative operator
- Formats a few unit test expected outputs to make diffing easier
- Updates said unit tests to reflect the above changes
- Changes conditional expressions (`e ? e : e`) from right-associative to left-associative (see example 1 [here](https://www.php.net/manual/en/language.operators.precedence.php)) and updates relevant unit tests
- Adds more unit tests to expressions.txt to test some common edge cases in PHP

In general, I tried to adhere to the [formal grammar](https://github.com/php/php-langspec/blob/master/spec/19-grammar.md) and only rely on [the docs](https://www.php.net/manual/en/language.operators.precedence.php) when necessary.

### CODE REVIEW

**Comment by KevOrr** [comment]
Also I'm not sure if I should re-run `tree-sitter generate` as part of this PR

**Comment by maxbrunsfeld** [comment]
> I'm not sure if I should re-run tree-sitter generate as part of this PR

Yeah, you should. We keep the generated code in the repo.

**Comment by KevOrr** [comment]
Done. Not sure why the build is failing. Looks like the same errors as in https://github.com/tree-sitter/tree-sitter/issues/362

**Comment by KevOrr** [comment]
I was able to get the Travis build working by [pinning the Node version to 11](https://github.com/KevOrr/tree-sitter-php/pull/1). Tried doing the same for Appveyor but it gives the same error.

Btw I'd like to see this merged. Is there anything more I can do to help?

**Comment by patrickt** [comment]
@KevOrr Thanks so much for this, and sorry that it’s been languishing. Can we start with merging https://github.com/KevOrr/tree-sitter-php/pull/1 into this repo? Once that lands, these builds should go green, I think.

**Comment by KevOrr** [comment]
Oh KevOrr#1 was me trying to get these two builds working. Doesn't seem to fix the AppVeyor build though. If you want to merge that PR, it's based off of this PR, but should be able to be cherry-picked

**Comment by patrickt** [comment]
@KevOrr This should pass the builders when you merge in `master`, since #40 has been merged.

**Comment by KevOrr** [comment]
@patrickt Awesome! Rebased on top of master

**Pull request merged**
