### PR TITLE
Split parser attempt #2

### LINKED ISSUE #168: Inject PHP code without PHP tags
Hello!

I'm trying (somewhat unsuccessfully, but trying nonetheless) to write a parser for the [Laravel Blade](https://laravel.com/docs/master/blade) templating system. I've captured the code content between the output directives (e.g., `{{ $fooBar->some_attribute }}`) but when I inject the content the parser thinks it (`$fooBar->some_attribute`) is just text.

If I do the following then the parser recognizes it as a variable and properly highlights it, however, this defeats the whole purpose of the templating system:
`{{ <?php $fooBar->some_attribute ?> }}`

Something similar occurs in markdown file with PHP fenced content:

E.g., here the php parser thinks the content is just text
image

whereas it's a variable assignment with the php tags
image

Is there a way to have the parser recognize the content as php without explicitly declaring the php tags?

Thanks!

### PR DESCRIPTION
**Pull request by calebdw**
Hello!

Please see https://github.com/tree-sitter/tree-sitter-php/pull/180 for previous discussions.

This is a rough draft at splitting the parser into two separate parsers: one for just PHP (`php_only` which allows top level statements, start/end tags are optional), and one that parsers both PHP and HTML (normal `php` parser).  The same pattern as [tree-sitter-typescript](https://github.com/tree-sitter/tree-sitter-typescript) which uses a common grammar definition for the two dialects.

On another note, I can't seem to get the highlight tests to pass---it keeps giving me the following message...any ideas?

```
syntax highlighting:
No language found for path ".../tree-sitter-php/php_only/test/highlight/literals.php"
```

CC: @cfroystad 

Closes #168 

Checklist:
- [x] All tests pass in CI
- [x] There are sufficient tests for the new fix/feature
- [x] Grammar rules have not been renamed unless absolutely necessary (x rules renamed)
- [x] The conflicts section hasn't grown too much (x new conflicts)
- [x] The parser size hasn't grown too much (master: STATE_COUNT, PR: STATE_COUNT) (check the value of STATE_COUNT in src/parser.c)

### CODE REVIEW

**Comment by cfroystad** [comment]
Thanks for sticking with this and more than that your patience! I'm hoping to be able to allocate time to be more responsive in the near future.

If you add the tree-sitter section to the package.json files in php and php_only, highlight tests will run:

For php_only: (for php, use the same as in main package.json)
```
"tree-sitter": [
    {
        "scope": "source.php",
        "file-types": [
            "php"
        ],
        "highlights": "../queries/highlights.scm",
        "tags": "../queries/tags.scm"
    }
  ]
```
In general I like the approach, but would like to have some of bindings experts look over it as well as have some of the organizations depending on the parser test the result before final merge. However, let's try to get this to a fully passing test suite in CI before pinging them if we can :slightly_smiling_face:

**Comment by CalebDW** [comment]
@cfroystad, no worries---I understand :)

Thanks for the highlight test fix! That made sense and it worked.

The pipeline passed once, but now it's failing for some reason...

**Comment by amaanq** [comment]
MacOS is scuffed because some runners are upgrading to python3.12, where distutils was removed but that's necessary for gyp, I'll upgrade the actions here so that windows/ubuntu don't depend on mac

**Comment by amaanq** [comment]
Alright, done. Rebasing might be a pain - sorry about that :grimacing: but I had a bunch of tidying/release stuff I wanted added anyways and I released 0.20.0 since 0.19.1 was over 2 years old

**Comment by calebdw** [comment]
@cfroystad, I hope you had a great holiday season!

It looks like #198 fixes the macos pipeline---can we ping some of the experts to get eyes on this issue?

Thanks!

**Comment by cfroystad** [comment]
Thanks for your patience! I'm here at last :slightly_smiling_face:

I've merged the CI fix and am happy to see all tests passing!

@aryx It seems to me like we're preserving backwards compatibility here, but do you see any issues for your semgrep integration? It's a while since I've been down that (very interesting) rabbit hole, but I guess it should work since it's the same approach as used by the JS and Typescript parsers?

**Comment by aryx** [comment]
Hopefully it's backward compatible and using the `php` parser works as before.

**Comment by calebdw** [comment]
@aryx, the grammar has not been changed, so `php` should continue to work

**Comment by EmranMR** [comment]
Yess 🥳  Amazing work @calebdw , thank you so much for implementing this!

**Pull request merged**
