### PR TITLE
PHP8: Adds support for nullsafe operator

### PR DESCRIPTION
**Pull request by cfroystad**
[RFC](https://wiki.php.net/rfc/nullsafe_operator)

Introduces support for the nullsafe operator

**New nodes:**

- nullsafe_member_access_expression
- nullsafe_member_call_expression

Example: 

```php
$country = $session?->user?->getAddress()?->country;
```

Is parsed into:
```
(expression_statement
    (assignment_expression
      (variable_name (name))
      (nullsafe_member_access_expression
        (nullsafe_member_call_expression
          (nullsafe_member_access_expression
            (variable_name (name))
            (name)
          )
          (name)
          (arguments)
        )
        (name)
      )
    )
  )
```

Checklist:
- [x] All tests pass in CI.
- [x] There are sufficient tests for the new fix/feature (see tests in expressions.txt)
- [x] Grammar rules have not been renamed unless absolutely necessary (0 rules renamed)
- [x] The conflicts section hasn't grown too much (0 new conflicts)
- [x] The parser size hasn't grown too much (master: 1664, PR: 1727)

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Ugh, sorry that it's so much extra work for you to maintain these parallel branches because of the checked-in generated files. That's something we want to address at some point, but it's hard to find the time.

**Review by maxbrunsfeld — APPROVED** [review]

**Comment by maxbrunsfeld** [comment]
Are you interested in having commit access to this repo @cfroystad? You're doing great work on this grammar.

**Comment by cfroystad** [comment]
No worries, I've encountered worse 🙂 An I right in assuming the work required to avoid checkin og generated files is more related to release prosess than this repository in particular?

I'll rebase come Monday afternoon (Norwegian time, that is).

Just to make sure I don't bite over more than I han chew: what would commit access entail?

**Comment by maxbrunsfeld** [comment]
> what would commit access entail?

I’d propose this: still make changes in PRs, but for PRs like this one, where you can be pretty confident in your solution, just go ahead and merge it after CI finishes green. For PRs where there are new conflicts, or which add a lot of new complexity to the grammar (or a huge amount of states to the parser), keep requesting reviews as you see fit?

Of course, No need to change your workflow if you’re already happy with it. I just think for certain PRs, you should feel free to merge them yourself.

**Comment by cfroystad** [comment]
That sounds like a good plan!

**Comment by maxbrunsfeld** [comment]
Ok, sent an invite.

**Pull request merged**
