### PR TITLE
Update bindings for rust to include HIGHLIGHT_QUERY

### PR DESCRIPTION
**Pull request by Jellyfrog**
Checklist:
- [x] All tests pass in CI
- [x] There are sufficient tests for the new fix/feature
- [x] Grammar rules have not been renamed unless absolutely necessary (0 rules renamed)
- [x] The conflicts section hasn't grown too much (0 new conflicts)
- [x] The parser size hasn't grown too much (master: 2330, PR: 2330)

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Could not verify the others (INJECTIONS_QUERY, etc) so didn't include them

**Comment by aryx** [comment]
I think the CI error is maybe related to https://github.com/tree-sitter/tree-sitter-java/pull/106
We should update to node 16 also here.

**Comment by Jellyfrog** [comment]
I bumped node in the same PR, hope you dont mind

**Comment by aryx** [comment]
as soon as github starts to work again, I'll approve and merge that :)

**Pull request merged**
